"""Del tag_rfid locaux

Revision ID: 0777b8a31014
Revises: 809c9e726a99
Create Date: 2025-08-24 17:09:25.520760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0777b8a31014'
down_revision = '809c9e726a99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locaux', schema=None) as batch_op:
        batch_op.drop_column('tag_rfid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locaux', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_rfid', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
