"""Add

Revision ID: 305e62b0b8da
Revises: c2dc06061fdd
Create Date: 2025-08-25 15:46:34.549374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '305e62b0b8da'
down_revision = 'c2dc06061fdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsable', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.drop_column('responsable')

    # ### end Alembic commands ###
