"""Add

Revision ID: 6e898c3bd445
Revises: b4eb27e68794
Create Date: 2025-08-23 16:41:33.462066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e898c3bd445'
down_revision = 'b4eb27e68794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salarie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('departement',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salarie', schema=None) as batch_op:
        batch_op.alter_column('departement',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
