"""Add

Revision ID: 809c9e726a99
Revises: 6e898c3bd445
Create Date: 2025-08-23 20:12:43.539698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '809c9e726a99'
down_revision = '6e898c3bd445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('statut', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('statut')

    # ### end Alembic commands ###
