"""Add mar mod

Revision ID: b4eb27e68794
Revises: 
Create Date: 2025-08-23 14:35:30.604901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4eb27e68794'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marque', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('modele', sa.String(length=150), nullable=True))
        batch_op.drop_column('zone_affectation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zone_affectation', sa.VARCHAR(length=150), nullable=True))
        batch_op.drop_column('modele')
        batch_op.drop_column('marque')

    # ### end Alembic commands ###
