"""Add comm

Revision ID: c2dc06061fdd
Revises: 0777b8a31014
Create Date: 2025-08-24 18:10:17.161481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2dc06061fdd'
down_revision = '0777b8a31014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sous_famille', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commentaire', sa.String(length=255), nullable=True))
        batch_op.drop_column('periode_depreciation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sous_famille', schema=None) as batch_op:
        batch_op.add_column(sa.Column('periode_depreciation', sa.INTEGER(), nullable=True))
        batch_op.drop_column('commentaire')

    # ### end Alembic commands ###
